apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yp8yw7ztg-nodejs
  janus-idp.io/tekton: yp8yw7ztg-nodejs
  backstage.io/kubernetes-id: yp8yw7ztg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yp8yw7ztg-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
