apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yp8yw7ztg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yp8yw7ztg-nodejs 
  name: yp8yw7ztg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: yp8yw7ztg-nodejs 
